### ISSUE TITLE
Doesn't seem to be working with Vimium.

### ISSUE THREAD

**Issue by gagsays** [aristidesfl/smoothkeyscroll#14]
Smooth key scroll doesn't seem to take any effect if Vim is selected. IJKL are still choppy and disabled mouse hover effect isn't making any difference. Enabling smooth scroll option in Vimium does make a difference, but I think that's not smoothkeyscroll at play, because scrolling is choppier compared to arrow keys.

**Comment by aristidesfl** [comment]
@gagsays Thank you for the report, I will investigate this issue with Vimium.

**Comment by aristidesfl** [comment]
Vimium is very agressive and prevents other apps, extensions and pages from listening to the the same keys it is already bound on. Smooth Key Scroll could do the same but it increases the risk of breaking other apps functionality.

The recommended way to solve this issue is to unmap the keys in Vimium options like so:
![screen shot 2016-04-18 at 05 01 33](https://cloud.githubusercontent.com/assets/208149/14592781/b99e071e-0522-11e6-82db-40c98d58d03c.png)
